services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.15


  celery_worker:
    build:
      context: .
      dockerfile: ./app/tasks/Dockerfile
    command: celery -A app.tasks.celery_tasks worker --loglevel=info -Q celery
    depends_on:
      - database
      - redis
    volumes:
      - .:/app
      - temp_data:/app/temp

  celery_beat:
    build:
      context: .
      dockerfile: ./app/tasks/Dockerfile
    command: celery -A app.tasks.celery_tasks beat --loglevel=info
    depends_on:
      - database
      - redis
    volumes:
      - .:/app

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
      - celery_worker
    volumes:
      - .:/app
      - temp_data:/app/temp

volumes:
  db_data:
    driver: local
  temp_data:
    driver: local